icons_format = "{icon} "

[theme.overrides]
idle_bg = "#181818"
info_bg = "#181818"
good_bg = "#181818"
warning_bg = "#181818"
critical_bg = "#181818"
separator_bg = "$181818"

[icons]
icons = "awesome4"

[[block]]
block = "sound"
show_volume_when_muted = true

[[block]]
block = "battery"
full_format = " $icon $percentage {$time |}"
format = " $icon $percentage {$time |}"

[[block]]
block = "disk_space"


[[block]]
block = "cpu"
format = "   $utilization "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi) "

[[block]]
block = "net"
device = "wlp0s20f3"
format = " $icon $signal_strength $ssid "

[[block.click]]
button = "left"
cmd = "alacritty --command nmtui"
[[block.click]]
button = "right"
cmd = "alacritty --command bluetuith"

[[block]]
block = "bluetooth"
mac = "1C:E6:1D:25:AB:65"
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "E5:B4:1B:88:85:D6"
disconnected_format = ""

[[block]]
block = "time"
interval = 1
format = "   $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S') "

[[block]]
block = "pomodoro"
notify_cmd = "dunstify '{msg}' --urgency=low"

